language: sh

addons:
  rethinkdb: '2.3.4'
  postgresql: 9.6
  snaps:
    - name: docker
      channel: latest/beta

before_install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
